department/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('UIC/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

project/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'projects'

urlpatterns = [
    path('create/project/', views.CreateNewProject, name='create_project'),
    path('upload/project/lists/', views.upload_project_lists, name='upload_project_lists'),
    path('request/project/form/', views.request_form, name='request_form'),
    path('requested/project/list', views.RequestedProjectList, name='request_project_list'),
    path('all/', views.AllProjects.as_view(), name='project_list'),

    path('<project_slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update/<project_slug>/', views.UpdateProject, name='update_project'),

    # path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<project_slug>/', views.ProjectDeleteView.as_view(), name='delete_project'),

    # path('all/students/', views.all_students.as_view(), name='all_students')
]

projectAllocation/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from . views import ErrorTemplateView
# from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view() , name='index'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('departments/', include("department.urls", namespace='departments')),
    path('students/', include("student.urls", namespace='students')),
    path('teachers/', include("teacher.urls", namespace='teachers')),
    path('projects/', include("project.urls", namespace='projects')),

    re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),

    path('selected/option/', views.getSelectedList, name='selected_option'),
    path('distribute/project/', views.genereteList, name='distributed_project_list'),

    path('<department_slug>/<student_slug>/profile/', views.student_detail_view, name='student_detail'),
    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students'),

    path('choose/project/<student_slug>/', views.distributeProjects, name='project_choice'),
    path('edit/project/<student_slug>/', views.editDistributedProjects, name='edit_project_choice'),



]

teacher/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('teacher/register/', views.teacher_register, name='teacher_register'),

    path('department/<department_slug>/profile/<teacher_slug>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('department/<department_slug>/teachers', views.TeacherList.as_view(), name='teacher_list'),
    path('update/profile/teacher/<teacher_slug>/', views.update_teacher_profile, name='update_teacher_profile'),
    path('delete/<department_slug>/teacher/<teacher_slug>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),

    path('all/teachers/', views.AllTeachers.as_view(), name='all_teachers')
]

department/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.
import misaka


class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    chairman = models.CharField(max_length=45, unique=True)
    detail = models.TextField()
    detail_html = models.TextField(editable=False)
    department_slug = models.SlugField(allow_unicode=True, unique=True)
    acronyms = models.CharField(max_length=10)
    established_date = models.DateTimeField(blank=True, null=True)

    created_by = models.ForeignKey(User, null=True, blank=True, related_name="department_created_by", on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, blank=True, related_name="department_updated_by", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name.upper()

    def save(self, *args, **kwargs):
        self.department_slug = slugify(self.name)
        self.detail_html = misaka.html(self.detail)

        self.name = self.name.upper()
        self.acronyms = self.name.replace("&", "").replace("AND", "").replace("OF", "")
        self.acronyms = "".join(ch[0] for ch in self.acronyms.split())
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("departments:department_detail",
                        kwargs={"department_slug" : self.department_slug})

    class Meta:
        ordering = ["name"]


def get_image_filename(instance, filename):
    name = instance.department.name
    slug = slugify(name)
    return "department_images/%s-%s" % (slug, filename)


class DepartmentImages(models.Model):
    department = models.ForeignKey(Department,related_name='department_images', default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='department_image')

department/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Department, DepartmentImages

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ('name', 'chairman', 'detail')


class DepartmentImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = DepartmentImages
        fields = ('image', )

department/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.forms import modelformset_factory
from django.contrib import messages

from . models import DepartmentImages, Department
from . forms import DepartmentForm, DepartmentImageForm
from django.contrib.auth.mixins import UserPassesTestMixin


# checks if the user requesting the page is superuser or not
class SuperUserCheck(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser


@login_required
def CreateDepartment(request):
    # using modelformset_factory, we can specify how many fields we want to add in the form
    # here, using extra=3, we are enabling the user to upload 3 images of department.
    ImageFormSet = modelformset_factory(model=DepartmentImages,
                                form=DepartmentImageForm, extra=3 )

    if request.method == 'POST':
        # if a user submits the form we get the items sent by the user by (request.user)
        departmentForm = DepartmentForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                            queryset=DepartmentImages.objects.none())

        # checking the form is valid or not. (Checking different type of validation declared in models.py file)
        if departmentForm.is_valid() and formset.is_valid():
            # here, we prevent the system to save details sent by user to the database as we need to manipulate the data.
            department_form = departmentForm.save(commit=False)
            department_form.created_by = request.user

            # collecting department name and established date from POST request
            dept_name = request.POST.get('name')
            established_date = request.POST.get('established_date')
            if established_date:
                print(established_date)
                department_form.established_date = established_date

            # after manipulating data, we save the information to database.
            department_form.save()

            from django.utils.text import slugify
            dept_slug = slugify(dept_name)

            for form in formset.cleaned_data:
                # this helps to not crash if the user
                # do not upload all the photos
                # we check that whether the user adds image of the particular department or not!
                if form:
                    image = form['image']
                    department_image = DepartmentImages(department=department_form, image=image)
                    department_image.save()

            # sending a success message to the user
            messages.success(request,
                        "Photos has been uploaded to departments section of media!")
            print("\n\n****dept: {}***/n/n".format(dept_slug))
            # redirecting the user to the department details page.
            return HttpResponseRedirect(reverse("departments:department_detail", kwargs={
                                                                "department_slug":dept_slug}))
        else:
            # if the form is not valid, then we show the user the errors.
            print(departmentForm.errors, formset.errors)
            departmentForm_errors = departmentForm.errors
            formset_errors = formset.errors
            return render(request, 'student/profileupdate_form.html', {
                'department_form': DepartmentForm,
                "formset":formset,
                'departmentForm_errors': departmentForm_errors,
                'formset_errors': formset_errors
            })
    else:
        # if user method is get, we simply send the forms to the user to fill them up
        departmentForm = DepartmentForm()
        formset = ImageFormSet(queryset=DepartmentImages.objects.none())
    return render(request, 'department/department_form.html', {
                            "department_form":departmentForm,
                            "formset":formset
                        })


class DepartmentDetail(DetailView):
    model = Department

    # gets the particular department and return it to the user
    def get_object(self, **kwargs):
        return get_object_or_404(
            Department,
            department_slug__iexact=self.kwargs['department_slug'],
        )


class DepartmentStudents(DetailView):
    # find the students admitted to that department
    model = Department
    slug_field = 'department_slug'
    slug_url_kwarg = 'department_slug'
    template_name = 'department/department_students.html'


class DepartmentTeachers(DetailView):
    # find the teachers belong to that department
    model = Department
    slug_field = 'department_slug'
    slug_url_kwarg = 'department_slug'
    template_name = 'department/department_teachers.html'


class UpdateDepartment(SuperUserCheck, UpdateView):
    model = Department
    fields = ('chairman', 'detail')
    template_name = 'department/department_update.html'

    def get_object(self, **kwargs):
        return get_object_or_404(
            Department,
            department_slug__iexact=self.kwargs['department_slug'],
            # access_key=self.kwargs['access_key'],
        )


class DepartmentDelete(SuperUserCheck, DeleteView):
    # declaring the model
    model = Department

    # after deleting the department, it redirects the user to the list of departments page.
    def get_success_url(self):
          return reverse_lazy("departments:all_departments")

    # gets the specific department to delete
    def get_object(self, **kwargs):
        return get_object_or_404(
            Department,
            department_slug__iexact=self.kwargs['department_slug'],
            # access_key=self.kwargs['access_key'],
        )

    # returns a message to the user
    def delete(self, *args, **kwargs):
        messages.success(self.request, "Department Deleted")
        return super().delete(*args, **kwargs)


class AllDepartments(ListView):
    # shows all departments in the university
    model = Department
    template_name = 'department/department_list.html'









###########

department/templates/department/department_base.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}

<br>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong> {{ message }} </strong>
        </div>
        {% endfor %}
      {% endif %}
    </div>

<div class="container card border border-dark" style="background-color:#f2f2f2; width: 65rem;">
  <div card-body>
      <br>
    {% block content %}

    {% endblock %}
  </div>
</div>


{% endblock %}

department/templates/department/department_confirm_delete.html
{% extends "department/department_base.html" %}

{% block content %}
<section id="steps" class="steps section-bg">
	<div class="container">
		<h3>Are you sure you want to delete <span style="color:#1bac91; font-size:22px">{{object.name}}</span>?</h3><br><br>

		<form method="POST">
			{% csrf_token %}

			<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
			<a href="{% url 'departments:department_detail' department_slug=department.department_slug %}" class="btn btn-primary btn-large">Cancel</a>

		</form>
	</div>
	<br> <br> <br>
</section>

{% endblock %}

department/templates/department/department_detail.html
{% extends "department/department_base.html" %}

{% block content %}

  <div class="container jumbotron">
    <h2>Welcome to Division detail page!</h2>

    <br> <ul>
      <h6>Total students: {{department.students.count }}</h6>
      <h6>Faculty members : {{department.teachers.count }}</h6>
    </ul>
    <br>
    <ul>
      <div class="row">
        <div class="col-lg-3 col-md-3">
          <h5><a class="btn btn-primary" href="{% url 'departments:department_teachers' department_slug=department.department_slug %}">Division Teachers</a> </h5>
        </div>
        <div class="col-lg-3 col-md-3">
          <h5><a class="btn btn-warning" href="{% url 'departments:department_students' department_slug=department.department_slug %}">Division Students</a> </h5>
        </div>
      </div>
    </ul>


    {% if user.is_superuser %}
    <ul>
      <div class="row">
        <div class="col-lg-3 col-md-3">
          <a class="btn btn-lg btn-primary" href="{% url 'departments:update_department' department_slug=department.department_slug %}">
             Update Div
          </a>
        </div>

      <div class="col-lg-3 col-md-3">
        <a class="btn btn-lg btn-danger" href="{% url 'departments:delete_department' department_slug=department.department_slug %}">
          <span class="fa fa-times-circle-o"></span> Delete Div
        </a>
      </div>
      </div>
    </ul>
    {% endif %}
  </div>

<div class="container">
  <h4>Name of the Division: <span style="color:#1bac91; font-size:19px">{{department.name}}</span> </h1>
  <ul>
    <li><h6>Acronym: {{department.acronyms}}</h2> </li>
    <li> <h6> Chairman : {{department.chairman}} </h3> </li>

    <li><h6>Total teachers : {{department.teachers.count}} </h2></li>
    <li><h6>Total students : {{department.students.count}} </h2></li>
    {% if department.established_date %}
      <li> <h6>Established at: {{department.established_date|time:"TIME_FORMAT"}}</h2> </li>
    {% endif %}
  </ul>
  <br><br>

  <br>
  <h5 style="color:#8a5030 ;"><strong>About {{department.name}}: </strong> </h5>
  <p style="color:#5c5b5a ;"> {{department.detail_html|safe}}</h4><br><br>
</div>


<section id="portfolio" class="portfolio section-bg">

    <div class="container">
      <div class="row portfolio-container" data-aos="fade-up">
        {% if department.department_images.count != 0 %}
        {% for img in department.department_images.all %}

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">

              <img src='{{ img.image.url }}' class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4>{{ department.name }}</h4>

                <div class="portfolio-links">
                  <a href="{{img.image.url}}" data-gall="portfolioGallery" class="venobox"><i class="bx bx-link"></i>Full Picture</a>
                </div>
              </div>

            </div>
        </div>
      {% endfor %}

      {% else %}
      <h5>No photos uploaded in <span style="color:#1bac91;">{{department.name}}</span>. This site is under
        maintenance.</h2>
      {% endif %}
    </div>
  </div>
  </section>

<br><br><br><br>



{% endblock %}

department/templates/department/department_form.html
{% extends "department/department_base.html" %}
{% load bootstrap4 %}

{% block content %}

<section id="steps" class="steps section-bg">
  <div class="container card border border-danger" style="background-color:#e0dada; width: 50rem; color:#8c000c">
    <div card-body>
      {% if departmentForm_errors or formset_errors %}
      <h4>Validation Error</h4>
      <h6>Check these fileds:</h6>
    {% endif %}

    {% if departmentForm_errors %}
      <ul>
        {% for error in departmentForm_errors %}
        <li>
          {{ error }}
        </li>
        {% endfor %}
      </ul>
    {% endif %}

    {% if formset_errors %}
      <ul>
        {% for error in formset_errors %}
        <li>
          {{ error }}
        </li>
        {% endfor %}
      </ul>
    {% endif %}

    </div>
  </div>

  <div class="container jumbotron">
    {% if user.is_superuser %}
    <form id="department_form" method="post" action="" enctype="multipart/form-data">

      {% csrf_token %}
      <h1>Create New Division</h1>

      {% for hidden in department_form.hidden_fields %}
          {{ hidden }}<br>
      {% endfor %}

      {% bootstrap_form department_form %}

      <div>
        <div class="form-group">
          <label for="established_date">Established Date</label>
          <input type="date" id="established_date" name="established_date"
            placeholder="dd-mm-yyyy" value=""
            min="1997-01-01" max="2030-12-31">
        </div>
      </div>


      <br>
      {{ formset.management_form }}
      {% for form in formset %}
          {{ form }}<br><br>
      {% endfor %}

      <br>
      <input type="submit" name="submit" value="Create Division" />
    </form>
    {% else %}
    <h2>You must be a superuser to Create Division</h2>
    {% endif %}
  </div>
</section>
<br><br>
{% endblock %}

department/templates/department/department_list.html
{% extends "department/department_base.html" %}

{% block content %}


<section id="steps" class="steps section-bg">
  <div class="container jumbotron">
    {% if department_list.count == 0 %}
      <h4>No Divisions created till now. This site is under construction.</h4>
    {% else %}
      <h4>Welcome to All Division page of UIC</h4>
      <h5>Number of Divisions : {{department_list.count}}</h5>
  </div>

  <div class="container">

    {% for department in department_list %}
      <hr>
      <ul>

        <li> <h4>Division: <a href="{% url 'departments:department_detail'  department_slug=department.department_slug %}"> {{department.name}}</h2></a> </li>
        <ul>
          <li> <h6> Chairman : {{department.chairman}} </h3> </li>
          <li><h6>Total teachers in {{department.name}} : {{department.teachers.count}} </h2></li>
          <li><h6>Total students in {{department.name}} : {{department.students.count}} </h2></li>
          <li> <h6>Established at: {{department.established_date}}</h2> </li>
        </ul>

      </ul><hr>
    {% endfor %}
  </div>
{% endif %}

</section>


{% endblock %}

department/templates/department/department_students.html
{% extends "department/department_base.html" %}

{% block content %}

  <div class="container jumbotron">

      <br>
    <h2>All Students of <a style="font-size:24px;" href="{% url 'departments:department_detail' department_slug=department.department_slug %}">{{department.name}}</a> </h2>

    <br><br>
    <h6><span style="font-weight:bold">Total students:</span> {{department.students.count }}</h2>

    <br>
    {# <h5> {{department.detail_html|safe}}</h4><br><br> #}

  </div>


  <div class="container">
    <section id="steps" class="steps section-bg" style="background-color:#fafcff">


      <hr>
      {% if department.students.count == 0 %}
        <h5>No students admitted in this department.</h5>

      {% else %}
    <div style="height:400px;overflow:auto;">
      <table id="details_table" style="text-align:center; " class="table table-bordered " align="center">
        <thead style="color:blue">
          <th> <p>Profile Pic</p> </th>
          <th> <p>Student Username </p> </th>
          <th> <p>Student ID</p> </th>
          <th> <p>Email</p> </th>
          <th><p> Division</p> </th>
          <th> <p>Session </p> </th>
        </thead>

        {% for student in department.students.all %}

        <tr >
          <td style="border:0px"><br> </td>
        </tr>

        <tr>
          {% if student.profile_pic %}
           <td><img src="{{ student.profile_pic.url }}"  height=120 width=120 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=120 width=120 alt=""></td>
          {% endif %}

          <td style="min-width:150px;"> <a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %} " style="color:#1bac91; font-size:19px"> {{student.user.username}}</a> </td>
          <td style="min-width:150px;"> {{ student.ID_Number }} </td>

          {% if student.user.email %}
            <td style="min-width:200px;"> <span style="color:#2f5b9c;"> {{student.user.email}}</span></td>
          {% else %}
            <td style="min-width:200px;"><p> <span style="color:#2f5b9c;">Not given </span></p> </td>
          {% endif %}

          <td style="min-width:200px;"> <a href="{% url 'departments:department_detail' department_slug=student.department.department_slug %}"> {{ student.department.acronyms }} </a> </td>
          <td style="min-width:150px;"><p> <span style="color:#2f5b9c;">{{student.session}}</p> </td>
        </tr>


        {% endfor %}
      </table>
    </div>
      {% endif %}

      <hr>

    </section>
  </div>

<br><br><br>

{% endblock %}

department/templates/department/department_teachers.html
{% extends "department/department_base.html" %}

{% block content %}

  <div class="container jumbotron">

      <br>
    <h2>All Teachers of <a style="font-size:24px;" href="{% url 'departments:department_detail' department_slug=department.department_slug %}">{{department.name}}</a> </h2>

    <br><br>
    <h6><span style="font-weight:bold">Total teachers:</span> {{department.teachers.count }}</h2>

    <br>
    {# <h5> {{department.detail_html|safe}}</h4><br><br> #}

  </div>


  <div >
    <section id="steps" class="container steps section-bg" style="background-color:#fafcff">

      {% if department.teachers.count == 0 %}
        <h5 style="padding-left:10px;">No teachers recruited in this department.</h5>

      {% else %}
      <div style="height:400px;overflow:auto;">
        <table id="details_table" style="text-align:center;" class="table table-bordered table-striped"  align="center">
        <thead style="color:blue; text-align:center;">
          <th> <p>Profile Pic </p></th>
          <th> <p>Username </p> </th>
          <th> <p>Academic Rank</p> </th>
          <th> <p>Teacher ID</p> </th>
          <th> <p>Email</p> </th>
          <th><p>Division</p> </th>
        </thead>

        {% for teacher in department.teachers.all %}
        <tr >
          <td style="border:0px"> </td>
        </tr>

        <tr>
          {% if teacher.profile_pic %}
           <td><img src="{{ teacher.profile_pic.url }}"  height=150 width=150 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=150 width=150 alt=""></td>
          {% endif %}

          <td style="min-width:120px;"> <a href="{% url 'teachers:teacher_detail' department_slug=teacher.department.department_slug teacher_slug=teacher.teacher_slug %} " style="color:#1bac91; font-size:19px"> {{teacher.user.username}} </a></td>
          <td style="min-width:150px;"> {{teacher.academic_rank}} </td>
          <td style="min-width:120px;"> {{ teacher.ID_Number }} </td>

          {% if teacher.user.email %}
            <td style="min-width:200px;"><p> <span style="color:#2f5b9c;"> {{teacher.user.email}}</p></td>
          {% else %}
          <td style="min-width:200px;"><p> <span style="color:#2f5b9c;">Not given </span></p> </td>
          {% endif %}

          <td style="min-width:150px;"> <a href="{% url 'departments:department_detail' department_slug=teacher.department.department_slug %}"> {{ teacher.department.name }} </a> </td>
        </tr>

        {% endfor %}
      </table>

      </div>
      {% endif %}

    </section>
  </div>

<br><br><br>

{% endblock %}

department/templates/department/department_update.html
{% extends "department/department_base.html" %}
{% load bootstrap4 %}

{% block content %}

    <section id="steps" class="steps section-bg">

      <div class="container">
        <h3>Update <span style="color:#1bac91; font-size:22px">{{ department.name }}</span> </h3>
          <br>
        <form method="POST" class="post-form">
        {% csrf_token %}

        {% bootstrap_form form %}


        <input type="submit" class="btn btn-primary">

        </form>
      </div>
    </section>


{% endblock %}