department/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('UIC/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

project/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'projects'

urlpatterns = [
    path('create/project/', views.CreateNewProject, name='create_project'),
    path('upload/project/lists/', views.upload_project_lists, name='upload_project_lists'),
    path('request/project/form/', views.request_form, name='request_form'),
    path('requested/project/list', views.RequestedProjectList, name='request_project_list'),
    path('all/', views.AllProjects.as_view(), name='project_list'),

    path('<project_slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update/<project_slug>/', views.UpdateProject, name='update_project'),

    # path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<project_slug>/', views.ProjectDeleteView.as_view(), name='delete_project'),

    # path('all/students/', views.all_students.as_view(), name='all_students')
]

projectAllocation/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from . views import ErrorTemplateView
# from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view() , name='index'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('departments/', include("department.urls", namespace='departments')),
    path('students/', include("student.urls", namespace='students')),
    path('teachers/', include("teacher.urls", namespace='teachers')),
    path('projects/', include("project.urls", namespace='projects')),

    re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),

    path('selected/option/', views.getSelectedList, name='selected_option'),
    path('distribute/project/', views.genereteList, name='distributed_project_list'),

    path('<department_slug>/<student_slug>/profile/', views.student_detail_view, name='student_detail'),
    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students'),

    path('choose/project/<student_slug>/', views.distributeProjects, name='project_choice'),
    path('edit/project/<student_slug>/', views.editDistributedProjects, name='edit_project_choice'),



]

teacher/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('teacher/register/', views.teacher_register, name='teacher_register'),

    path('department/<department_slug>/profile/<teacher_slug>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('department/<department_slug>/teachers', views.TeacherList.as_view(), name='teacher_list'),
    path('update/profile/teacher/<teacher_slug>/', views.update_teacher_profile, name='update_teacher_profile'),
    path('delete/<department_slug>/teacher/<teacher_slug>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),

    path('all/teachers/', views.AllTeachers.as_view(), name='all_teachers')
]

student/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Student

class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    Confirm_Password = forms.CharField(label='confirm your password',widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(StudentForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("Confirm_Password")

        if password == '':
            raise forms.ValidationError(
                "Please, Enter a valid password"
            )

        if password != confirm_password:
            print(password)
            print(confirm_password)
            print("do not match")
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

        if not cleaned_data.get("email"):
            raise forms.ValidationError(
                "Please Enter valid Email address"
            )



class StudentProfileInfoForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ('ID_Number', 'supervisor', 'session', 'department', 'profile_pic')

    def __init__(self, *args, **kwargs):
        super(StudentProfileInfoForm, self).__init__(*args, **kwargs)
        self.fields['department'].label = "Division"

student/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.utils.text import slugify
from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.utils.text import slugify

from .forms import StudentForm, StudentProfileInfoForm
from .models import Student
from teacher.models import Teacher
from department.models import Department


def student_register(request):
    registered = False

    if request.method == 'POST':
        # collecting the information sent
        student_form = StudentForm(data=request.POST)
        student_profile_form = StudentProfileInfoForm(data=request.POST)

        if student_form.is_valid() and student_profile_form.is_valid():
            # Save User Form to Database
            user = student_form.save()

            # Hash the password so that no one can see the password, not even the admin
            user.set_password(user.password)

            # Now we deal with the extra info!
            # Can't commit yet because we still need to manipulate
            student_profile = student_profile_form.save(commit=False)

            if not request.user.is_anonymous:
                student_profile.created_by = request.user
            # Set One to One relationship between
            # StudentForm and StudentProfileInfoForm
            student_profile.user = user

            if 'profile_pic' in request.FILES:
                student_profile.profile_pic = request.FILES['profile_pic']

            # now saving the models
            user.save()
            student_profile.save()

            name = request.POST.get('username')
            dept_id=request.POST.get('department')

            # getting the department where the student belongs
            department = get_object_or_404(Department, pk=dept_id)
            from django.utils.text import slugify
            student_slug = slugify(name)
            # converting the name into slug field, so that we can use this field to
            # generate url for student detail page
            dept_slug = slugify(department.name)

            return HttpResponseRedirect(reverse('students:student_detail', kwargs={'department_slug':dept_slug, 'student_slug':student_slug}))
        else:
            print(student_form.errors, student_profile_form.errors)
            # if the form is not valid, shows the error to the user
            return render(request, 'student/student_registration.html', {
                'student_form': student_form,
                'student_profile_form': student_profile_form,
                'user_form_errors': student_form.errors,
                'student_profile_form_errors': student_profile_form.errors
            })
    else:
        # if the requested method is get, then simply send empty forms to the user to fill those up.
        student_form = StudentForm()
        student_profile_form = StudentProfileInfoForm()

    return render(request, "student/student_registration.html",context={
                    'student_form':student_form,
                    'student_profile_form':student_profile_form,
                    'registered':registered})



class StudentDetailView(SelectRelatedMixin, DetailView):
    select_related = ("user", "department")
    # declaring the name of the object (student_detail) using which we can get student data.
    context_object_name = 'student_detail'
    model = Student
    template_name = 'student/student_detail.html'

    def get_object(self, **kwargs):
        # gets the particular student object, otherwise returns 404
        return get_object_or_404(
            Student,
            student_slug=self.kwargs['student_slug']
        )


from project.models import *
def student_detail_view(request, student_slug, department_slug):
    # gets the particular student object, otherwise returns 404
    student_detail = get_object_or_404(
            Student,
            student_slug=student_slug
        )

    assigned_project = student_detail.assigned_project_name
    try:
        # getting the project that is assigned to the particular student and
        # the project choices, selected by the student.
        project = Project.objects.get(name=student_detail.assigned_project_name)
        projectChoice = ProjectChoice.objects.filter(student_id=student_detail.id)
    except:
        # if no project is assigned to the student, then assign null
        project = ""
        projectChoice = ""

    try:
        requested_project = ProjectRequestProposal.objects.get(created_by=student_detail.id)
    except:
        requested_project = ""

    # print("requested_project : ", requested_project)
    return render(request, 'student/student_detail.html', context={
        'student_detail': student_detail,
        'assigned_project': assigned_project,
        'project':project,
        'projectChoice':projectChoice,
        'department_slug':department_slug,
        'student_slug':student_slug,
        'requested_project':requested_project,
    })


class StudentList(SelectRelatedMixin, ListView):
    # get all student object from database
    model = Student
    select_related = ("user", "department")


global user_profile_form
def getForms(request, model, slug_instance, UserForm, UserProfileInfoForm):
    if request.method == 'POST':
        if not request.user.is_superuser:
            # if user is student then we pass that user as the instance
            user_form = UserForm(request.POST, instance=request.user)
            if model == Student:
                # print("student")
                user_profile_form = UserProfileInfoForm(request.POST, instance=request.user.student)
                department_slug = request.user.student.department.department_slug
            else:
                # print("teacher")
                # if user is teacher then we pass that user as the instance
                user_profile_form = UserProfileInfoForm(request.POST, instance=request.user.teacher)
                department_slug = request.user.teacher.department.department_slug

            return user_form, user_profile_form, department_slug
        else:
            print("admin")
            # if the user is superuser, then we get the student and teacher model using slug field
            # collected from the url
            if model == Student:
                instance = model.objects.get(student_slug=slug_instance)
            else:
                instance = model.objects.get(teacher_slug=slug_instance)

            # now, we pass the Student/Teacher (instance.user) as instance
            user_form = UserForm(request.POST, instance=instance.user)
            profile_form = UserProfileInfoForm(request.POST, instance=instance)
            department_slug = instance.department.department_slug
            return user_form, profile_form, department_slug
    else:
        if not request.user.is_superuser:
            # if the method is get and the user is not superuser, we pass the user as instance
            user_form = UserForm(instance=request.user)
            if model == Student:
                user_profile_form = UserProfileInfoForm(instance=request.user.student)
            else:
                user_profile_form = UserProfileInfoForm(instance=request.user.teacher)

            return user_form, user_profile_form
        else:
            print("admin")
            # if the user is superuser, then we get the student and teacher model using slug field
            # collected from the url
            if model == Student:
                instance = model.objects.get(student_slug=slug_instance)
            else:
                instance = model.objects.get(teacher_slug=slug_instance)
            # now, we pass the Student/Teacher as instance
            user_form = UserForm(instance=instance.user)
            profile_form = UserProfileInfoForm(instance=instance)
            return user_form, profile_form


from django.db import transaction
@login_required
@transaction.atomic
def update_student_profile(request, student_slug):

    if request.method == 'POST':
        # collecting forms using getForms function
        user_form, student_profile_form, department_slug = getForms(request, model=Student,
                                                                    slug_instance=student_slug,
                                                                    UserForm=StudentForm,
                                                                    UserProfileInfoForm=StudentProfileInfoForm)

        if user_form.is_valid() and student_profile_form.is_valid():
            # checking the forms are valid or not
            # we do not save the user as we need to manipulate some data
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])

            student_profile_form.save(commit=False)
            student_profile_form.updated_by = request.user

            # after manipulating the data we save the information to the database
            user.save()
            student_profile_form.save()

            # we send a a success message
            messages.success(request, ('Your profile is successfully updated!'))
            return redirect(reverse('students:student_detail', kwargs={

student/templates/student/_student.html
<div class="media">

	<div class="media-body">
		<strong><a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %}"> {{ student.user.username }}</a> </strong>

    <ol>
	  <li> {{ student.user.username  }} </li>
      <li> {{ student.student_ID  }} </li>
      <li> {{ student.email  }} </li>
      <li> <a href="{% url 'departments:detail' faculty_slug=student.department.faculty.faculty_slug department_slug=student.department.department_slug %}">{{ student.department.name }}</a> </li>
      <li> <a href="{% url 'faculties:detail' faculty_slug=student.department.faculty.slug %}">{{ student.department.faculty.name }}</a> </li>
      <li> {{ student.session }} </li>
    </ol>


		<div class="media-footer">
			{% if user.is_superuser %}
				<a href="{% url 'students:student_delete' department_slug=student.department.department_slug student_slug=student.student_slug %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

student/templates/student/all_students.html
{% extends "department/department_base.html" %}

{% block content %}

  <div class="container jumbotron">

    <h3>All students are listed below</h3>
    <h6>Total students in UIT: <span style="font-size:22px;">{{students.count}}</span> </h6>
    <br>
    {# <h5> {{department.detail_html|safe}}</h5><br><br> #}

  </div>

{% if students %}
  <div class="container table-responsive">
    <section id="steps" class="steps section-bg" style="background-color:#fafcff">


      <hr>
    <div style="height:400px;overflow:auto;">
      <table style="border: 1px solid black;" id="details_table" class="table table-bordered table-striped" align="center">
        <thead >
          <th> Profile Pic </th>
          <th> Student Username </th>
          <th> Student ID </th>
          <th> Email </th>
          <th> Division </th>
          <th> Session  </th>
        </thead>

        {% for student in students %}
        <tr >
          <td style="border:0px"><br> </td>
        </tr>

        <tr style="border: 1px solid black;">
          {% if student.profile_pic %}
           <td><img src="{{ student.profile_pic.url }}"  height=120 width=120 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=120 width=120 alt=""></td>
          {% endif %}

          <td style="min-width:200px;"> <a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %} " style="color:#1bac91; font-size:19px"> {{student.user.username}}</a> </h4></td>
          <td style="min-width:100px;"> {{ student.ID_Number }} </td>

          {% if student.user.email %}
            <td> <span style="color:#2f5b9c;"> {{student.user.email}}</span></td>
          {% else %}
            <td> <span style="color:#2f5b9c;">Not given </span></td>
          {% endif %}

          <td style="min-width:150px;"> <a href="{% url 'departments:department_detail' department_slug=student.department.department_slug %}"> {{ student.department.name }} </a> </td>
          <td style="min-width:120px;"> <span style="color:#2f5b9c;">{{student.session}} </span> </td>
        </tr>

        <tr >
        </tr>
        <tr >
        </tr>
        {% endfor %}
      </table>
    </div>
      <hr>

    </section>
  </div>

<br><br><br>
{% endif %}


{% endblock %}

student/templates/student/change_password.html
{% extends "student/student_base.html" %}
{% load bootstrap4 %}
{% block content %}
<form class="" action="index.html" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}

  {{form}}

  {% buttons %}
    <button class="btn btn-primary" type="submit" name="button">Change Password</button>
  {% endbuttons %}
</form>

{% endblock %}

student/templates/student/distributed_list.html
{% extends "department/department_base.html" %}

{% block content %}

  <div class="container jumbotron">

    <h3>Students are assigned project based on the availability and order of selection</h3>
    <h6>Total students in UIT: <span style="font-size:22px;">{{ student_projects|length }}</span> </h6>
    <br>

  </div>

{% if student_projects %}
  <div class="container table-responsive">
    <section id="steps" class="steps section-bg" style="background-color:#fafcff">


      <hr>
    <div style="height:600px;overflow:auto;">
      <table style="border: 1px solid black; text-align:center;"  id="details_table" class="table table-bordered " align="center">
        <thead >
          <th> Student Username </th>
          <th> Student ID </th>
          <th> Email </th>
          <th> Division </th>
          <th> Session  </th>
          <th> Supervisor Name </th>
          <th> Assigned Project Title (Must be filled)</th>
          <th style="width:300px;"> Aim (MUST be Filled: SMART)</th>
          <th style="width:300px;"> Equipment/software Required</th>
          <th style="width:400px;"> Lab/  Room (Have you spoken to the relevant technician)</th>
          <th> Cohort </th>
        </thead>

        {% for object in student_projects %}


        <tr style="border: 1px solid black;">

          <td> <a href="{% url 'students:student_detail' department_slug=object.student.department.department_slug student_slug=object.student.student_slug %} " style="color:#1bac91; font-size:19px"> {{ object.student.user.username}}</a> </h4></td>
          <td style="min-width:130px;"> {{ object.student.ID_Number }} </td>

          {% if object.student.user.email %}
            <td> <span style="color:#2f5b9c;"> {{object.student.user.email}}</span></td>
          {% else %}
            <td> <span style="color:#2f5b9c;">Not given </span></td>
          {% endif %}

          <td style="min-width:150px;"> <a href="{% url 'departments:department_detail' department_slug=object.student.department.department_slug %}"> {{ object.student.department.name }} </a> </td>
          <td style="min-width:100px;"> <span style="color:#2f5b9c;">{{object.student.session}} </span> </td>
          <td style="min-width:150px;"> <span style="color:#2f5b9c;">{{object.student.supervisor.user.username}} </span> </td>

          {% if object.project.name %}
          <td style="min-width:200px;"> <span style="color:#2f5b9c;">{{object.project.name}} </span> </td>
          {% else %}
          <td style="min-width:200px; text-align:left;"> <span style="color:red; "> Isn't assigned with any projects.
            <a class='btn btn-primary' href="{% url 'students:project_choice' student_slug=object.student.student_slug %}">
            <span class="fa fa-times-circle-ok"></span> Choose Project</a>
          </span> </td>
          {% endif %}

          {% if object.project.project_details %}
          <td style="min-width:400px; text-align:justify;"> <span style="color:#2f5b9c; ">{{object.project.project_details}} </span> </td>
          {% else %}
          <td style="min-width:400px;"> <span style="color:#2f5b9c; "> None </span> </td>
          {% endif %}

          {% if object.project.software_required %}
          <td style="min-width:400px; text-align:justify;"> <span style="color:#2f5b9c; ">{{object.project.software_required}} </span> </td>
          {% else %}
          <td style="min-width:400px;"> <span style="color:#2f5b9c; "> None </span> </td>
          {% endif %}

          {% if object.project.lab %}
          <td style="min-width:400px; text-align:justify;"> <span style="color:#2f5b9c; ">{{object.project.lab}} </span> </td>
          {% else %}
          <td style="min-width:400px;"> <span style="color:#2f5b9c; "> None </span> </td>
          {% endif %}

            {% if object.divisions %}
          <td>
            {% for department in object.divisions %}
            <h6 style="color:#2f5b9c;"> {{ forloop.counter }}. {{ department.name }} </h6>
            <br>
            {% endfor %}
          </td>
            {% else %}
          <td style="min-width:400px;"> <span style="color:#2f5b9c; "> None </span> </td>
            {% endif %}
        </tr>

        {% endfor %}
      </table>
    </div>

      <hr>

    </section>
    <br>
    <button id="btnExport" class="btn btn-primary">
        Download .xls file
    </button>
  </div>

<br><br><br>
{% endif %}

<script>

$(document).ready(function(){
    $("#btnExport").click(function() {
    console.log("working")
        let table = document.getElementsByTagName("table");
        TableToExcel.convert(table[0], { // html code may contain multiple tables so here we are refering to 1st table tag
           name: `Distribued-list.xlsx`, // fileName you could use any name
           sheet: {
              name: 'Sheet 1' // sheetName
           }
        });
    });
});

  console.log("working")
</script>

{% endblock %}

student/templates/student/student_base.html
{% extends "base.html" %}

{% block body_block %}
<br>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong> {{ message }} </strong>
        </div>
        {% endfor %}
      {% endif %}
    </div>

<div class="container card border border-dark" style="background-color:#f2f2f2; width: 65rem;">
  <div card-body>
      <br>
    {% block content %}

    {% endblock %}
  </div>
</div>

{% endblock %}

student/templates/student/student_detail.html
{% extends "student/student_base.html" %}
{% block content %}
{% load static %}
<div class="container jumbotron">

<h1>Welcome to the Student Detail Page</h1><br><br>


<section id="portfolio" class="portfolio section-bg">

<div class="container">
  <div class="portfolio-container" data-aos="fade-up">
    <div class="row">
          <div class="col-lg-4 col-md-6 portfolio-item filter-faculty">
      <div class="portfolio-wrap">
            {% if student_detail.profile_pic %}
             <img class="img-fluid" src="{{ student_detail.profile_pic.url }}" alt="">

             <div class="portfolio-info">
               <h4>{{ student.department }}</h4>

             <div class="portfolio-links">
               <h5><a href='{{ student_detail.profile_pic.url }}' title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
             </div>

           </div>

            {% else %}
              <img class="img-fluid" style="width: 80%;background-size: contain; height: 100px; " src="/static/no_profile_pic.png" alt="">
            {% endif %}

      </div>
    </div>

    <div class="col-lg-8 col-md-6 portfolio-item ">
      <table id="details_table_teacher">
        <tr>
          <td> <p>Student Username: </p> </td>
          <td><p><span style="color:#2f5b9c;">{{student_detail.user.username}}</span></p> </td>
        </tr>

        <tr>
          <td> <p>Student ID: </td>
          <td> <span style="color:#2f5b9c;">{{student_detail.ID_Number}}</span></p> </td>
        </tr>

        <tr>
          <td> <p>Email: </td>
          {% if student_detail.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{student_detail.user.email}}</span></p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</span></p> </td>
          {% endif %}
        </tr>

        <tr>
          <td> <p>Supervisor:  </td>
          <td><span style="color:#2f5b9c;"><a href="{% url 'teachers:teacher_detail' department_slug=student_detail.department.department_slug teacher_slug=student_detail.supervisor.teacher_slug %}">{{student_detail.supervisor}} </a> </span> </td>
        </tr>

        <tr>
          <td> <p>Division:  </td>
          <td><span style="color:#2f5b9c;"><a href="{% url 'departments:department_detail' department_slug=student_detail.department.department_slug %}">{{student_detail.department}} </a> </span> </td>
        </tr>

        <tr>
          <td><p>Session: </p> </td>
          <td><p> <span style="color:#2f5b9c;">{{student_detail.session}}</p> </td>
        </tr>
      </table>


      </div>
    </div>


    <br> <br>
      {% if assigned_project %}
        <br><h5>Projects Choosen:</h5>

        <ul>
        {% for choice in projectChoice %}
          <li> <a href="{% url 'projects:project_detail' project_slug=choice.project.project_slug %}"> {{ choice.project.name }} </a></li>
        {% endfor %}
        </ul>
            <h3 style="color:#910c03; font-weight:bold; margin-left:20px; margin-right:10px;"> The project you have got is:
         <span> <a href="{% url 'projects:project_detail' project_slug=project.project_slug %}">{{ assigned_project }} </a></span> </h3>


        <br><br>
<!--        <a class='btn btn-primary' style="margin-left:20px;" href="{% url 'students:edit_project_choice' student_slug=student_detail.student_slug %}">-->
<!--         Edit Project Choice</a>-->

      {% elif user.teacher or user == student_detail.user or user.is_superuser %}
    <h4 style="margin-left:20px;"> <span style="color:#2f5b9c;">{{student_detail.user.username}} </span> haven't choose any projects</h4>

        <a class='btn btn-primary' style="margin-left:20px;" href="{% url 'students:project_choice' student_slug=student_detail.student_slug %}">
        <span class="fa fa-times-circle-ok"></span> Choose Project</a>
      {% endif %}

      <br><br>
    <div style="border:2px solid gray; ">
      {% if requested_project %}
      <h4 style="margin:4px 4px 4px 4px;"><span style="color:#2f5b9c;">{{student_detail.user.username}}'s </span> requested proposal to the <a href="{% url 'teachers:teacher_detail' department_slug=student_detail.department.department_slug teacher_slug=student_detail.supervisor.teacher_slug %}">supervisor:</a>  </h4>
        <ul>
          <li> <span style="color:#910c03; font-weight:bold;">Title:</span> {{requested_project.name}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Details:</span> {{requested_project.details}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Software Required:</span> {{requested_project.software_required}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Lab:</span> {{requested_project.lab}} </li>
        </ul>
      {% endif %}
    </div>

    </div>

  </div>
</div>
</section>


{% if user.is_authenticated and user.username == student_detail.user.username or user.is_superuser %}
<div class="container">
  <a class='btn btn-warning' href="{% url 'students:update_student_profile' student_slug=student_detail.student_slug %}">
    <span class="fa fa-times-circle-ok"></span> Update Profile</a>
  <a class='btn btn-danger' href="{% url 'students:delete_student' department_slug=student_detail.department.department_slug student_slug=student_detail.student_slug %}">
    <span class="fa fa-times-circle-ok"></span> Delete Profile</a>

</div>
{% endif %}
<br><br>

{% endblock %}