department/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('UIC/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

project/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'projects'

urlpatterns = [
    path('create/project/', views.CreateNewProject, name='create_project'),
    path('upload/project/lists/', views.upload_project_lists, name='upload_project_lists'),
    path('request/project/form/', views.request_form, name='request_form'),
    path('requested/project/list', views.RequestedProjectList, name='request_project_list'),
    path('all/', views.AllProjects.as_view(), name='project_list'),

    path('<project_slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update/<project_slug>/', views.UpdateProject, name='update_project'),

    # path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<project_slug>/', views.ProjectDeleteView.as_view(), name='delete_project'),

    # path('all/students/', views.all_students.as_view(), name='all_students')
]

projectAllocation/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from . views import ErrorTemplateView
# from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view() , name='index'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('departments/', include("department.urls", namespace='departments')),
    path('students/', include("student.urls", namespace='students')),
    path('teachers/', include("teacher.urls", namespace='teachers')),
    path('projects/', include("project.urls", namespace='projects')),

    re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),

    path('selected/option/', views.getSelectedList, name='selected_option'),
    path('distribute/project/', views.genereteList, name='distributed_project_list'),

    path('<department_slug>/<student_slug>/profile/', views.student_detail_view, name='student_detail'),
    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students'),

    path('choose/project/<student_slug>/', views.distributeProjects, name='project_choice'),
    path('edit/project/<student_slug>/', views.editDistributedProjects, name='edit_project_choice'),



]

project/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from department.models import Department
from student.models import Student


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        # fields = ['name', 'date', 'members']
        fields = ['name', 'project_details', 'can_be_taken_by',
                  'software_required', 'lab']

    # departments = forms.ModelMultipleChoiceField(
    #     queryset=Department.objects.all(),
    #     widget=forms.CheckboxSelectMultiple
    # )


class ProjectRequestProposalForm(forms.ModelForm):
    class Meta:
        model = ProjectRequestProposal
        exclude = ['created_by', 'supervisor']

project/views.py
from django.shortcuts import render, redirect,get_object_or_404

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
import xlrd

from django.forms import ModelForm
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory

from .forms import *
from .models import *
from department.models import Department

from django.db import transaction


@login_required
@transaction.atomic
def CreateNewProject(request):
    # declaring a glocal variable
    global instance
    # gets all objects of department model
    departments = Department.objects.all()
    try:
        # check if the user is superuser or the user is teacher
        if request.user.is_superuser or request.user.teacher:
            if request.method == 'GET':
                form = ProjectForm()
                # print("create - get method")

                return render(request, "project/project_form.html",
                              context={'form': form,
                                       'departments': departments,
                                       })

            elif request.method == 'POST':
                # we get the information sent by the user using request.POST
                project_form = ProjectForm(data=request.POST)

                if project_form.is_valid():
                    # if the information sent by the user is valid, then we save info to the database.
                    instance = project_form.save()

                    # check if user selects multiple projects or not
                    try:
                        # get the list of ids of departments
                        selected_departments = request.POST.getlist("departments")
                    except:
                        # get a single id of department
                        selected_departments = request.POST.get("departments")

                    print(selected_departments)
                    # print(instance.id)

                    for department_id in selected_departments:
                        try:
                            # create DepartmentProject object for every if in selected_departments
                            DepartmentProject.objects.create(project=instance,
                                                             department_id=int(department_id))
                        except Exception as ex:
                            print("second exception: ", ex)
                            # deleting the project
                            # if any exception occurs, delete the project object
                            project = Project.objects.get(id=instance.id)
                            project.delete()
                            messages.error(request, ('Check these errors'))
                            return render(request, 'project/project_form.html', context={
                                'form': ProjectForm(data=request.POST),
                                'departments': departments,
                                'formErrors': ex})
                else:
                    # if the form is not valid, it show the errors to the user
                    messages.error(request, ('Check these errors'))
                    return render(request, 'project/project_form.html', context={
                        'form': ProjectForm(data=request.POST),
                        'departments': departments,
                        'formErrors': ProjectForm.errors})

            print(instance.project_slug)
            # if everything is okay, then redirect the user to the project details page.
            return redirect(reverse('projects:project_detail',
                                    kwargs={"project_slug": instance.project_slug}))
    except Exception as ex:
        print("first exception: ", ex)
        return HttpResponse("You must be a superuser or Teacher to create a project")


@transaction.atomic
def UpdateProject(request, project_slug):
    global instance
    # getting the project and all departments from the database
    departments = Department.objects.all()
    project = Project.objects.get(project_slug=project_slug)
    # filtering departments under that particular project and getting ids of those departments.
    choosen_depts = DepartmentProject.objects.filter(project_id=project.id)
    choosen_depts_id = [dept.department.id for dept in choosen_depts]

    try:
        if request.user.is_superuser or request.user.teacher:
            if request.method == 'GET':
                # getting the project form and passing the instance to get the previous data from the database
                form = ProjectForm(instance=project)
                print("create - get method")

                return render(request, "project/project_update.html",
                              context={'form': form,
                                       'project':project,
                                       'departments': departments,
                                       "choosen_depts_id": choosen_depts_id,
                                       })

            elif request.method == 'POST':
                print("post ")
                # getting the values sent by the user
                project_form = ProjectForm(data=request.POST, instance=project)

                if project_form.is_valid():
                    # after checking the form validation, we save the updates to the database
                    instance = project_form.save()

                    try:
                        # getting the list of ids sent by the user
                        selected_departments = request.POST.getlist("departments")
                    except:
                        # getting a single id sent by the user
                        selected_departments = request.POST.get("departments")
                    print("selected_departments ", selected_departments)
                    # print(instance.id)

                    # getting the previous departments added under the particular project and
                    # delete those before saving updates.
                    DepartmentProject.objects.filter(project=instance).delete()
                    for department_id in selected_departments:
                        try:
                            # creating new object/ saving departments under the particular project
                            DepartmentProject.objects.create(project=instance,
                                                             department_id=int(department_id))
                        except Exception as ex:
                            print("second exception: ", ex)

                            # deleting the project
                            # if exception occurs, delete the project
                            project = Project.objects.get(id=instance.id)
                            project.delete()

                            messages.error(request, ('Check these errors'))
                            return render(request, 'project/project_update.html', context={
                                'form': ProjectForm(data=request.POST),
                                'departments': departments,
                                'formErrors': ex})
                else:
                    print("else part")
                    # if the form is not valid, show the errors to the user
                    messages.error(request, ('Check these errors'))
                    return render(request, 'project/project_update.html', context={
                        'form': ProjectForm(data=request.POST, instance=project),
                        'departments': departments,
                        'formErrors': ProjectForm.errors})

                print("project_slug ", instance.project_slug)
                return HttpResponseRedirect(reverse('projects:project_detail',
                                        kwargs={"project_slug": instance.project_slug}))
        else:
            raise Exception
    except Exception as ex:
        print("first exception: ", ex)
        return HttpResponse("You must be a superuser or Teacher to create a project")


class ProjectDetailView(DetailView):
    model = Project
    context_object_name = 'project_details'
    template_name = 'project/project_detail.html'

    def get_object(self, **kwargs):
        # gets the particular object from the database to show it to the user
        print(self.kwargs)
        project = Project.objects.get(
            project_slug=self.kwargs['project_slug']
        )
        print(project)
        return project


class AllProjects(ListView):
    # ListView collects all projects from the database
    model = Project
    context_object_name = "projects"
    template_name = 'project/project_list.html'


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/user/login/'
    template_name = 'project/project_confirm_delete.html'
    model = Project

    # get the particular project to delete
    def get_object(self, **kwargs):
        return Project.objects.get(project_slug=self.kwargs['project_slug'])

    # shows the list of projects page, after successfully deleting the project from the database
    def get_success_url(self):
          return reverse_lazy('projects:project_list')


@login_required
def upload_project_lists(request):
    if request.method == 'GET':

project/templates/project/project_base.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}
<br>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong> {{ message }} </strong>
        </div>
        {% endfor %}
      {% endif %}
    </div>

<div class="container card border border-dark" style="background-color:#f2f2f2; width: 65rem;">
  <div card-body>
      <br>
    {% block content %}

    {% endblock %}
  </div>
</div>
 <br><br>

{% endblock %}

project/templates/project/project_confirm_delete.html
{% extends "department/department_base.html" %}

{% block content %}
<section id="steps" class="steps section-bg">
	<div class="container">
		<h3>Are you sure you want to delete <span style="color:#1bac91; font-size:22px">{{object.name}}</span>?</h3><br><br>

		<form method="POST">
			{% csrf_token %}

			<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
			<a href="{% url 'projects:project_detail' project_slug=object.project_slug %}" class="btn btn-primary btn-large">Cancel</a>

		</form>
	</div>
	<br> <br> <br>
</section>

{% endblock %}

project/templates/project/project_detail.html
{% extends "department/department_base.html" %}

{% block content %}

  <div class="container jumbotron">
    <h2>Welcome to Project detail page!</h2>

    <br>
    <ul>
      <h6>Total students: {{project_details.students.count }}</h6>
      <h6>Total Departments : {{project_details.departments.count }}</h6>
    </ul>
    <br>

    {% if user.is_superuser or user.teacher %}
    <ul>
      <div class="row">
        <div class="col-lg-3 col-md-3">
          <a class="btn btn-lg btn-primary" href="{% url 'projects:update_project' project_slug=project_details.project_slug %}">
            <span class="fa fa-times-circle-ok"></span> Update Project
          </a>
        </div>

      <div class="col-lg-3 col-md-3">
        <a class="btn btn-lg btn-danger" href="{% url 'projects:delete_project' project_slug=project_details.project_slug %}">
          <span class="fa fa-times-circle-o"></span> Delete Project
        </a>
      </div>
      </div>
    </ul>
    {% endif %}
  </div>

<div class="container">
  <h4>Name of the Project: <span style="color:#1bac91; font-size:19px">{{project_details.name}}</span> </h4>
  <ul>

    <li><span style="color:#8a5030 ;"><strong>About : </strong> </span>{{ project_details.project_details|safe }}</li>
    <li><span style="color:#8a5030 ;"><strong>Software Required : </strong> </span>{{ project_details.software_required|safe }}</li>
    <li><span style="color:#8a5030 ;"><strong>lab : </strong> </span>{{ project_details.lab|safe }}</li>
    <li><span style="color:#8a5030 ;"><strong>taken : </strong> </span>{{ project_details.taken|safe }}</li>
    <li><span style="color:#8a5030 ;"><strong>Can be taken by : </strong> </span>{{ project_details.can_be_taken_by|safe }}</li>
    <li><span style="color:#8a5030 ;"><strong>Available : </strong> </span>{{ project_details.available|safe }}</li>

  </ul>
  <br><br>

</div>


<section id="portfolio" class=" section-bg">

    <div class="container">
      <h4>Divisions: </h4>
      <div class="row ">

        {% if project_details.departments.count != 0 %}
        <br>
        <ul>
        {% for department in project_details.departments.all %}

        <div class="col-lg-12 col-md-12 ">
          <li><a href="{% url 'departments:department_detail' department_slug=department.department_slug %}">{{ department.name }}</a></li>
        </div>
        {% endfor %}
        </ul>

      {% else %}
      <h5>No Divisions added in <span style="color:#1bac91;">{{project_details.name}}</span>. This site is under
        maintenance.</h2>
      {% endif %}
    </div>
  </div>
  </section>

<br><br><br><br>



{% endblock %}

project/templates/project/project_form.html
{% extends "department/department_base.html" %}
{% load bootstrap4 %}

{% block content %}


<section id="steps" class="steps section-bg">
  <div class="container jumbotron">
     <div class="container card border border-danger" style="background-color:#e0dada; width: 50rem; color:#8c000c">
    <div card-body>
      {% if formErrors %}
      <h4>Validation Error</h4>
      <h6>Check these fileds:</h6>
    {% endif %}

    {% if formErrors %}
      <ul>
        {% for error in formErrors %}
        <li>
          {{ error }}
        </li>
        {% endfor %}
      </ul>
    {% endif %}

    </div>
  </div>


    {% if user.is_superuser or user.teacher %}
    <form id="project_form" method="post" action="" enctype="multipart/form-data">

      {% csrf_token %}
      <h1>Create New Project</h1>

      {% bootstrap_form form %}

      <h6>Choose Divisions</h6>
      <select name="departments" class="selectpicker department"
              multiple title="Choose one of the following..."
              data-live-search="true"
              data-actions-box="true">
        {% for department in departments %}
          <option value={{department.id}}> {{department.name}}</option>
        {% endfor %}
      </select>


      <br><br>
      <input type="submit" name="submit" value="Create Project" />
    </form>
    {% else %}
    <h2>You must be a superuser to Create Project</h2>
    {% endif %}
  </div>
</section>

<br><br>
{% endblock %}



<script>
  $( document ).ready(function() {
    $('.department').selectpicker();
  });
</script>

project/templates/project/project_list.html
{% extends "department/department_base.html" %}

{% block content %}


<section id="steps" class="steps section-bg">
  <div class="container jumbotron">
    {% if projects.count == 0 %}
      <h4>No projects created till now. This site is under construction.</h4>
    {% else %}
      <h4>Welcome to All project page of UIC</h4>
      <h5>Number of projects : {{projects.count}}</h5>
  </div>

  <div class="container">

    {% for project in projects %}
      <hr>
      <ul>

        <li> <h4> <a href="{% url 'projects:project_detail' project_slug=project.project_slug %}">{{project.name}}</a> </h4></a> </li>
        <ul>
          <li> <h6>{{project.project_details}} </h6> </li>

          <ul>
            {% if project.departments.count != 0 %}
              <li> Division having this project: {{project.departments.count}}</li>

            {% else %}
              <li>No Divisions added!</li>
            {% endif %}
          </ul>
        </ul>

      </ul><hr>
    {% endfor %}
  </div>
{% endif %}

</section>


{% endblock %}

project/templates/project/project_update.html
{% extends "department/department_base.html" %}
{% load bootstrap4 %}

{% block content %}

    <section id="steps" class="steps section-bg">

      <div class="container">
        <h3>Update <span style="color:#1bac91; font-size:22px">{{ project.name }}</span> </h3>
          <br>
        <form method="POST" class="post-form">
        {% csrf_token %}

        {% bootstrap_form form %}

      <h6>Choose Divisions</h6>
      <select name="departments" class="selectpicker department"
              multiple title="Choose one of the following..."
              data-live-search="true"
              data-max-options="3"
              data-actions-box="true">
        {% for department in departments %}
          <option value={{department.id}}> {{department.name}}</option>
        {% endfor %}
      </select>


      <br><br><br><br>
      <input type="submit" name="submit" value="Edit Project" />
      <br><br><br><br>
        </form>
      </div>
    </section>

<script>

$('.selectpicker').selectpicker('val', {{ choosen_depts_id }});
</script>

{% endblock %}

project/templates/project/request_form.html
{% extends "department/department_base.html" %}
{% load bootstrap4 %}

{% block content %}


<section id="steps" class="steps section-bg">
  <div class="container jumbotron">
     <div class="container card border border-danger" style="background-color:#e0dada; width: 50rem; color:#8c000c">
    <div card-body>
      {% if formErrors %}
      <h4>Validation Error</h4>
      <h6>Check these fileds:</h6>
    {% endif %}

    {% if formErrors %}
      <ul>
        {% for error in formErrors %}
        <li>
          {{ error }}
        </li>
        {% endfor %}
      </ul>
    {% endif %}

    </div>
  </div>

    {% if user.student or user.is_superuser %}
    <form id="project_form" method="post" action="" enctype="multipart/form-data">

      {% csrf_token %}
      <h1>Request your project idea to your supervisor</h1>

      {% bootstrap_form form %}

      <br><br>
      <input type="submit" name="submit" value="Request to supervisor" />
    </form>
    {% else %}
    <h2>You must be a student to request your supervisor for a project</h2>
    {% endif %}
  </div>
</section>

<br><br>
{% endblock %}

project/templates/project/requested_project_list.html
{% extends "department/department_base.html" %}

{% block content %}


<section id="steps" class="steps section-bg">

{% if requested_projects %}
  <div class="container">
    {% for requested_project in requested_projects %}
      <hr>
      <ul>
          <li> <span style="color:#910c03; font-weight:bold;">Title:</span> {{requested_project.name}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Details:</span> {{requested_project.details}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Software Required:</span> {{requested_project.software_required}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Lab:</span> {{requested_project.lab}} </li>
          <li> <span style="color:#910c03; font-weight:bold;">Requested by:</span> <a href="{% url 'students:student_detail' department_slug=requested_project.created_by.department.department_slug student_slug=requested_project.created_by.student_slug %}"> {{requested_project.created_by}} </a> </li>
      </ul><hr>
    {% endfor %}
  </div>

{% else %}
    <div style="text-align:center; ">
         <h5> <span style="color:#910c03; font-weight:bold;"> You don't have any requested projects from any students. </span></h5>
    </div>

{% endif %}

</section>


{% endblock %}

project/templates/project/upload_project_lists.html
{% extends "department/department_base.html" %}
{% load bootstrap4 %}

{% block content %}


<section id="steps" class="steps section-bg">
  <div class="container jumbotron">

    {% if user.is_superuser or user.teacher %}
    <form id="project_form" method="post" action="" enctype="multipart/form-data">

      {% csrf_token %}
      <h1>Upload Project excel file</h1>
      <h5>Follow this column sequence in the excel file for creating new projects.</h5>
      <ol>
        <li>Name</li>
        <li>Project Detail</li>
        <li>Can be taken</li>
        <li>Software Required</li>
        <li>Lab</li>
        <li>Divisions</li>
      </ol>

        <input type="file" name="projectLists" />

      <br><br>
      <input type="submit" name="submit" value="Upload excel file" />
    </form>
    {% else %}
    <h2>You must be a superuser or Teacher to Create Project</h2>
    {% endif %}
  </div>
</section>

<br><br>
{% endblock %}



<script>

</script>