department/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('UIC/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

project/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'projects'

urlpatterns = [
    path('create/project/', views.CreateNewProject, name='create_project'),
    path('upload/project/lists/', views.upload_project_lists, name='upload_project_lists'),
    path('request/project/form/', views.request_form, name='request_form'),
    path('requested/project/list', views.RequestedProjectList, name='request_project_list'),
    path('all/', views.AllProjects.as_view(), name='project_list'),

    path('<project_slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update/<project_slug>/', views.UpdateProject, name='update_project'),

    # path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<project_slug>/', views.ProjectDeleteView.as_view(), name='delete_project'),

    # path('all/students/', views.all_students.as_view(), name='all_students')
]

projectAllocation/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from . views import ErrorTemplateView
# from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view() , name='index'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('departments/', include("department.urls", namespace='departments')),
    path('students/', include("student.urls", namespace='students')),
    path('teachers/', include("teacher.urls", namespace='teachers')),
    path('projects/', include("project.urls", namespace='projects')),

    re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),

    path('selected/option/', views.getSelectedList, name='selected_option'),
    path('distribute/project/', views.genereteList, name='distributed_project_list'),

    path('<department_slug>/<student_slug>/profile/', views.student_detail_view, name='student_detail'),
    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.update_student_profile, name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students'),

    path('choose/project/<student_slug>/', views.distributeProjects, name='project_choice'),
    path('edit/project/<student_slug>/', views.editDistributedProjects, name='edit_project_choice'),



]

teacher/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('teacher/register/', views.teacher_register, name='teacher_register'),

    path('department/<department_slug>/profile/<teacher_slug>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('department/<department_slug>/teachers', views.TeacherList.as_view(), name='teacher_list'),
    path('update/profile/teacher/<teacher_slug>/', views.update_teacher_profile, name='update_teacher_profile'),
    path('delete/<department_slug>/teacher/<teacher_slug>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),

    path('all/teachers/', views.AllTeachers.as_view(), name='all_teachers')
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>PAS</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


  <!-- Favicons -->
  <link href='{% static "assets/img/logo_small.jpg" %}' rel="icon">
  <!-- <link href='{% static "assets/img/apple-touch-icon.png" %}' rel="apple-touch-icon"> -->

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


  <!-- Template Main CSS File -->
  <link href='{% static "assets/css/style.css" %}' rel="stylesheet">
<!--  <link href='{% static "css/main.css" %}' rel="stylesheet">-->

  <!--  contains multiple select picker-->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>




<!--  export excel file-->
  <script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>

</head>

<style>
  .bootstrap-select {
      width: 600px !important;
  }

  .navbar .nav-item .dropdown-menu{ display: none; }
	.navbar .nav-item:hover .nav-link{ color: #fff;  }
	.navbar .nav-item:hover .dropdown-menu{ display: block; }
	.navbar .nav-item .dropdown-menu{ margin-top:0; }


  body {
      font-family: Merriweather, Georgia, "times new roman", serif;
      color: #222;
    }


    font{
        font-style: normal;
        font-variant-ligatures: normal;
        font-variant-caps: normal;
        font-variant-numeric: normal;
        font-variant-east-asian: normal;
        font-weight: 400;
        font-stretch: normal;
        font-size: 18px;
        line-height: 1.8;
        font-family: Merriweather, Georgia, "times new roman", serif;
    }

    p {
        display: block;
        margin-block-start: 1em;
        margin-block-end: 1em;
        margin-inline-start: 0px;
        margin-inline-end: 0px;
        text-align: justify;
        margin-top: 0px;
        margin-bottom: 1rem;
    }


    a {
      color: #1bac91;
    }

    a:hover {
      color: #22d8b6;
      text-decoration: none;
    }

    h1, h2, h3, h4, h5, h6 {
      font-family: Merriweather, Georgia, "times new roman", serif;
    }
  }
</style>

<body>
  <!-- ======= Header ======= -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid">
    <div class="row container">
      <div class="col-md-3">
        <div class="navbar-header" >
          <a style="font-size:25px;" class="navbar-brand" href='{% url "index" %}'>Project Allocation System</a>
        </div>

      </div>


      <div class="col-md-2">  </div>

      <div class="col-md-7" style="float:right;">
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class=" navbar-nav dropdown" >
            <li class="nav-item active ">
              <a class="nav-link" href='{% url "index" %}'>Home</a>
            </li>

            <li class="nav-item dropdown dropdown2">
              <a class="nav-link dropdown-toggle " href="/#departments" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Division
              </a>
              <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'departments:create_department' %}">Create Division</a>
                <a class="dropdown-item" href="{% url 'departments:all_departments' %}">All Division</a>
              </div>
            </li>

            <li class="nav-item dropdown dropdown2">
              <a class="nav-link dropdown-toggle " href="/#departments" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Project
              </a>
              <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'projects:create_project' %}">Create Project</a>
                <a class="dropdown-item" href="{% url 'projects:upload_project_lists' %}">Upload Project lists</a>
                <a class="dropdown-item" href="{% url 'projects:request_form' %}">Request to supervisor</a>
                <a class="dropdown-item" href="{% url 'projects:project_list' %}">All Projects</a>
                <a class="dropdown-item" href="{% url 'students:distributed_project_list' %}">Distributed Project List</a>
              </div>
            </li>

            <li class="nav-item dropdown dropdown2">
              <a class="nav-link dropdown-toggle " href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Student & Teachers
              </a>
              <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'students:all_students' %}">Students</a>
                <a class="dropdown-item" href="{% url 'teachers:all_teachers' %}">Teachers</a>
              </div>
            </li>

            <li class="nav-item dropdown dropdown2">
                <a class="nav-link dropdown-toggle " href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Register
                </a>
                <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">

                    <a class="dropdown-item" href="{% url 'students:student_register' %}"> New Student</a>
                    <a class="dropdown-item" href="{% url 'teachers:teacher_register' %}"> New Teacher</a>

                </div>
              </li>

            {% if user.is_authenticated  %}

              {% if user.is_superuser %}
            <li class="nav-item dropdown dropdown2">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Status: Superuser
                </a>
                <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">

                  <a class="dropdown-item" href="/admin/">Admin</a>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>

              {% elif user.teacher.ID_Number %}
            <li class="nav-item dropdown dropdown2">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Status: Teacher
                </a>
                <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">

                  <a class="dropdown-item" href="{% url 'teachers:teacher_detail' department_slug=user.teacher.department.department_slug teacher_slug=user.teacher.teacher_slug %}">Profile</a>
                  <a class="dropdown-item" href="{% url 'projects:request_project_list' %}">Requested project list</a>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>

              {% elif user.student.ID_Number %}
            <li class="nav-item dropdown dropdown2">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Status: Student
                </a>
                <div class="dropdown-menu dropdown-content" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'students:student_detail' department_slug=user.student.department.department_slug student_slug=user.student.student_slug %}">Profile</a>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
              {% endif %}

              {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'user_login' %}">Login</a>
            </li>

              {% endif %}

          </ul>
        </div>

      </div>

      <div class="col-md-0" style="width:80px;
                                    height:80px;
                                    top:10px;
                                    right:10px;
                                    z-index: 3;
                                    position:absolute;">
              <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>

    </div>
  </div>
</nav>

  <div style="padding-top:100px;">
  {% block body_block %}

  {% endblock %}
  </div>
  <br>

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">

            <div class="footer-info" style="text-align:center;">
              <h3> &#169; PAS -
              <span>
                University Project allocation system <br>
              </span>
                </h3>
            </div>

        </div>
    </div>

  </footer><!-- End Footer -->


</body>

</html>

templates/error.html
{% extends "base.html" %}
{% block body_block %}
<br><br>
<section id="steps" class="steps section-bg">
  <br><br>

  <div class="container jombotron">

    <h1 id="notfound">Sorry</h1>
    <h3 id="notfound"> 404 - Page Not Found! </h3>
    <br><br>

  </div>
<br><br>

</section>
<br><br>


<style>

#notfound{
  color: red;
  text-align: center;
}
</style>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
  <div class="container text-center text-md-left" data-aos="fade-up">
    <h1>Welcome to Final Year Project Allocation System</h1>
    <h2 style="text-align:justify;">This is a project allocation application where a student can choose
    3 projects based on his/her rank of choice. Projects will be distributed based on
    the order of student's choice.</h2>
    <a href="{% url 'projects:project_list' %}" class="btn-get-started scrollto">Projects</a>
  </div>
</section><!-- End Hero -->

<main id="main">

</main>

{% endblock %}

templates/registration_options.html
{% extends "base.html" %}
{% block body_block %}
<br><br>
<section id="steps" class="steps section-bg">
  <br><br>
  <div class="container jombotron">
    <h1>Welcome to Registration page!</h1><br><br>
    <ul>
      <li><h4>Register as a Student: <a class="btn btn-primary" href="{% url 'students:student_register' %}">Student Registration</a></h2> </li>
    </ul>

    <ul>
      <li><h4>Register as a Teacher: <a class="btn btn-primary" href="{% url 'teachers:teacher_register' %}">Teacher Registration</a></h4> </li>
    </ul>

    <br><br>
    <h5>If you have completed registration already then click this
      link to go to <a href="{% url 'user_login' %}">Login page</a> </h5>
  </div>
<br><br>

</section>
<br><br>


{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block body_block %}

<div class="container jumbotron">
  <br>
  <h1>Thanks for visiting! Come back soon!</h1><br><br><br><br>
</div>

{% endblock %}

templates/user_login.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block body_block %}
<section  id="steps" class="steps section-bg">

  <div class="container jumbotron">
      {% if messages %}

        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong> {{ message }} </strong>
        </div>
        {% endfor %}

      {% endif %}

    <h1>Login</h1>

    <form method="POST" class="form">
      {% csrf_token %}
            {# A more "HTML" way of creating the login form#}

        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter Username">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>


    </form>
  </div>

<div class="container">
  <h5>If you aren't a registered student or teacher, please go to registration
    page to complete your registration.
  <a style="text-decoration:underline;" href="{% url 'registration_options' %}">Registration</a> </h5>

</div>
</section>
{% endblock %}